### ISSUE TITLE
Delete an Incident

### ISSUE THREAD

**Issue by r1de** [DanRuderman/EmComMap#6]
Is there a way to remove an incident?
Even though the test incident I created has expired I am still able to select it and it's there and I am still able to add things to it.

**Comment by DanRuderman** [comment]
The notion of an incident is that of a time range and a rectangular region of geography. It's a space-time filter. Now, there are locations you can create that are tied to an incident, meaning you won't see them on the map before or after the incident. But there isn't really a way to lock down an incident so that nothing changes.

As far as deleting an incident, that you could only do via the database directly right now. So eventually the selection box of incidents will get cluttered with everything. I think they are sorted by most recent at the top. At some point there should probably be an event overview/admin page.
